### ISSUE TITLE
Namespace problems

### ISSUE THREAD

**Issue by JordanYates** [onomondo/nrf-softsim#15]
There are several examples of functions that are not properly namespaced to this repo, which are almost certain to cause issues for someone in the future with an ecosystem as large as Zephyrs'. By this, I mean the name is so generic that other libraries and application could easily write code with the same name.

In the same vein, there are a few internal variables without a `static` qualifier which could cause compilation issues for users.

Namespace issues:
- `aes_128_encrypt_block`
- `read_nvs_to_cache`
- `fs_is_initialized`
- `init_fs`
- `deinit_fs`
- `port_*`
- `hex_to_uint8`
- `hex_string_to_bytes`
- `decode_profile`

Static issues:
- `shared_buffer` 
- `softsim_work_q`
- `ctx`
- `storage_path`

**Comment by peterbornerup** [comment]
Thanks for addressing these issues. I've opened a ticket internally.
