### ISSUE TITLE
Serial LTE Modem application (nRF Connect SDK) crashes during SoftSIM DEINIT

### ISSUE THREAD

**Issue by MirkoCovizzi** [onomondo/nrf-softsim#23]
Hi,

we are currently encountering a problem where when issuing a `CFUN=0` after a `CFUN=1` the application core will reboot due to a crash in the `DEINIT` switch case, in particular while executing the `deinit_fs` function.

To reproduce the bug, checkout the branch https://github.com/MirkoCovizzi/nrf-softsim/tree/deinit-crash, point the manifest to `west.yml` and do a `west update`.
This will pull the NCS branch https://github.com/MirkoCovizzi/sdk-nrf/tree/deinit-crash that contains the application (currently WIP) https://github.com/MirkoCovizzi/sdk-nrf/tree/deinit-crash/applications/serial_lte_modem_softsim.

To build the application:
* Go to the application directory: `applications/serial_lte_modem_softsim`
* Execute: `west build -b nrf9160dk_nrf9160_ns -- -DOVERLAY_CONFIG=overlay-onomondo.conf`

To test the application:
* Open a serial terminal to UART0
* Check that upon boot the application will output the string `Ready`
* Issue the following command into the serial terminal: `AT+CFUN=1`
* Issue the following command into the serial terminal: `AT+CFUN=0`
* Observe that the application will reboot, showing the string `Ready`

To show that the `deinit_fs` function is the culprit, checkout https://github.com/MirkoCovizzi/nrf-softsim/tree/deinit-no-crash and repeat the steps above.
Observe that after executing the same steps, the application will not reboot due to a crash (will not output the string `Ready`) after the specific sequence of AT commands.

**Comment by peterbornerup** [comment]
I believe this is fixed in the newest release [v2.2.1](https://github.com/onomondo/nrf-softsim/releases/tag/v2.2.1)

We had an old `free` not changed to use `k_free`.  It's been changed to use the `SS_FREE` macro now.

**Comment by MirkoCovizzi** [comment]
@peterbornerup Thanks Peter, looks like it fixes the issue. Best regards.
